/* ============================================================
   data.js — Global i18n strings
   Load this BEFORE app-core.js and app-sa.js
============================================================ */

const I18N = {
  en: {
    tab_seating: 'Seating', tab_picker: 'Name Picker',
    pov_teacher: 'Teacher POV', pov_student: 'Student POV',
    pov_teacher_label: "Teacher's View", pov_student_label: "Student's View",
    btn_shuffle: 'Shuffle', btn_skip_anim: 'Skip', btn_students: 'Students', btn_settings: 'Settings',
    btn_apply: 'Apply', btn_done: 'Done', btn_cancel: 'Cancel', btn_save: 'Save Changes',
    btn_close: 'Close', btn_export: 'Export', btn_import: 'Import',
    btn_pick: 'Pick!', btn_clear_history: 'Clear History',
    btn_add_student: 'Add Student', btn_bulk_add: 'Save List',
    btn_stats: 'Stats', btn_undo_pick: 'Undo', btn_sort_alpha: 'A-Z', btn_sort_status: 'Status',
    stat_total: 'Total Students', stat_present: 'Present', stat_absent: 'Absent',
    stat_seats: 'Active Seats', stat_occupancy: 'Occupancy',
    btn_all_present: '✓ All Present', btn_all_absent: '✗ All Absent',
    btn_reset: 'Reset Defaults', btn_upload_bg: 'Upload', btn_clear_bg: 'Clear',
    btn_clear_all: 'Clear All',
    seating_title: 'Seating Chart', teacher_desk: "🖥️ Teacher's Desk",
    label_rows: 'Rows:', label_cols: 'Cols:', label_name: 'Full Name',
    label_gender: 'Gender', label_status: 'Attendance', label_bulk: 'Student Names',
    opt_male: 'Male', opt_female: 'Female', opt_present: 'Present', opt_absent: 'Absent',
    hint_bulk: 'Edit freely. New names are added, removed names deleted, existing kept.',
    modal_students_title: 'Manage Students', modal_edit_title: 'Edit Student',
    modal_settings_title: 'Settings',
    stab_list: 'Student List', stab_add: 'Add Student', stab_bulk: 'Bulk Add',
    picker_title: '🎲 Random Name Picker',
    picker_subtitle: 'Picks a random student from those present',
    picker_placeholder: 'Press Pick to start!',
    allow_repeat: 'Allow repeat picks',
    history_title: 'Pick History', history_empty: 'No picks yet. Start picking!',
    settings_data: 'Data Management', settings_appearance: 'Appearance', settings_danger: 'Danger Zone',
    settings_export: 'Export Data', settings_export_desc: 'Save all data as a .json backup file',
    settings_import: 'Import Data', settings_import_desc: 'Load a previously exported .json file',
    settings_bg: 'Custom Background', settings_bg_desc: 'Upload an image as page background (auto-compressed)',
    settings_pov: 'Point of View', settings_pov_desc: 'Flip seating grid orientation',
    settings_clear_all: 'Clear All Data', settings_clear_all_desc: 'Wipe all localStorage data and reset to defaults',
    ctx_lock: 'Lock Seat', ctx_unlock: 'Unlock Seat',
    ctx_disable: 'Disable Seat', ctx_enable: 'Enable Seat',
    ctx_gender: 'Toggle Gender', ctx_assign: 'Assign Student',
    word_students: 'students', word_undo: 'Undo',
    btn_attendance: 'Attendance', btn_view_rekap: 'View Report',
    btn_rekap_nilai: 'Grade Report', modal_rekap_nilai_title: 'Grade Report',
    lbl_include_zero: 'Include 0 scores',
    tab_nilai_siswa: 'Per Student', tab_nilai_hari: 'Per Day',
    tab_nilai_minggu: 'Per Week', tab_nilai_ringkasan: 'Summary',
    lbl_quiz_weekly: 'Weekly Quiz', lbl_quiz_daily: 'Daily Quiz',
    lbl_nilai_label: 'Score', lbl_avg: 'Average',
    lbl_weekly_avg: 'Weekly Avg', lbl_class_avg: 'Class Avg',
    lbl_no_nilai: 'No score data yet.',
    toast_nilai_saved: 'Scores saved!', settings_rekap_desc: 'View & print attendance report by period', modal_attendance_title: 'Daily Attendance',
    modal_rekap_title: 'Attendance Report', label_att_date: 'Date',
    btn_all_hadir: 'All Present', btn_all_alpa: 'All Absent',
    btn_save_att: 'Save Attendance', btn_filter: 'Filter',
    btn_print: 'Print', btn_del_date: 'Delete Date',
    att_hadir: 'Present', att_sakit: 'Sick', att_izin: 'Excused', att_alpa: 'Absent',
    btn_edit_formasi: 'Edit Layout', btn_done_formasi: '✓ Done',
    btn_mark_absent_one: 'Mark Absent', btn_mark_present_one: 'Mark Present',
    toast_att_saved: 'Attendance saved!', toast_att_deleted: 'Date deleted.',
    toast_att_no_date: 'Please select a date first.',
    rekap_no_data: 'No attendance data yet.',
    col_name: 'Name', col_total_H: 'Present', col_total_S: 'Sick',
    col_total_I: 'Excused', col_total_A: 'Absent', col_total: 'Total',
    row_summary: 'Summary',
    toast_undo_empty: 'Nothing to undo.',
    toast_sort_alpha: 'Sorted A-Z.', toast_sort_status: 'Sorted by status.',
    toast_reset_confirm: 'Reset to default students?',
    toast_clear_confirm: 'This will erase ALL data. Continue?',
    toast_bg_uploading: 'Saving background to cloud...',
    toast_bg_local: 'Background saved locally only.',
    toast_fix_gender: 'genders updated!', toast_fix_gender_ok: 'All genders are correct.',
    toast_class_delete_confirm: 'Delete class? Data cannot be recovered.',
    toast_class_empty_name: 'Enter a class name first!',
    sync_saving: 'Syncing', sync_saved: 'Online', sync_error: 'Sync failed', sync_offline: 'Offline',
    picker_eligible: 'eligible', picker_picks: 'picks',
    toast_shuffled: 'Seats shuffled!', toast_locked_seats: 'locked seats kept.',
    toast_no_students: 'No present students to shuffle.',
    toast_student_added: 'Student added!', toast_student_updated: 'Student updated!',
    toast_student_deleted: 'Student deleted.',
    toast_bulk_added: 'students added!', toast_all_present: 'All students marked present.',
    word_added: 'added', word_removed: 'removed', word_total: 'total',
    toast_all_absent: 'All students marked absent.',
    toast_reset: 'Reset to default students.',
    toast_exported: 'Data exported successfully!', toast_imported: 'Data imported successfully!',
    toast_import_error: 'Invalid file. Could not import.',
    toast_bg_set: 'Background image set!', toast_bg_cleared: 'Background cleared.',
    toast_cleared: 'All data cleared. Fresh start!',
    toast_no_eligible: 'No eligible students to pick!',
    toast_all_picked: 'All students have been picked! Clear history or enable repeats.',
    status_present: 'Present', status_absent: 'Absent',
    eligible_label: 'eligible',
    picks_label: 'picks',
    // Superadmin panel strings
    sa_title: 'Superadmin Panel',
    sa_loading: 'Loading...',
    sa_loading_users: 'Loading users...',
    sa_loading_classes: 'Loading all classes...',
    sa_loading_class: 'Loading classes...',
    sa_loading_class_data: 'Loading class data...',
    sa_no_users: 'No users found.',
    sa_no_classes: 'No classes registered yet.',
    sa_no_classes_match: 'No matching classes.',
    sa_no_user_classes: 'This user has no classes yet.',
    sa_no_att_data: 'No attendance data yet.',
    sa_no_score_data: 'No score data yet.',
    sa_no_students: 'No students.',
    sa_you_label: 'You',
    sa_view_classes_btn: '📚 Classes',
    sa_promote_btn: '⬆ Make Admin',
    sa_demote_btn: '⬇ Make User',
    sa_confirm_revoke_admin: 'Remove superadmin rights from this user?',
    sa_role_changed: 'Role changed to "{role}".',
    sa_err_change_role: 'Failed to change role: ',
    sa_err_load: 'Failed to load: ',
    sa_err_delete_class: 'Failed to delete: ',
    sa_confirm_delete_class: 'Delete class "{name}" owned by {user}?\nData will be permanently lost.',
    sa_class_deleted: 'Class "{name}" deleted.',
    sa_classes_summary: 'Total',
    sa_classes_summary2: 'users',
    sa_classes_owned_by: 'Classes owned by:',
    sa_back_to_users: '← Back to Users',
    sa_back_to_classes: '← Back',
    sa_by: 'by',
    sa_update: 'Updated:',
    sa_col_students: 'Students',
    sa_col_att_days: 'Attendance Days',
    sa_col_score_days: 'Score Days',
    sa_tab_rekap_att: '📋 Attendance Report',
    sa_tab_rekap_nilai: '📊 Score Report',
    sa_tab_students: '👥 Student List',
    sa_create_class_btn: 'Create Class',
    sa_footer: 'Only superadmins can access this panel.',
    sa_lbl_recent_activity: 'Recent activity',
    sa_tab_dashboard: 'Dashboard',
    sa_tab_users: 'Users',
    sa_tab_classes: 'Classes',
    sa_tab_logs: 'Logs',
    sa_tab_settings: 'Settings',
    sa_lbl_total_users: 'Total Users',
    sa_lbl_total_classes: 'Total Classes',
    sa_lbl_total_students: 'Total Students',
    sa_lbl_active_today: 'Active Today',
    sa_lbl_recent_users: 'Recent Users',
    sa_search_users_placeholder: 'Search users...',
    sa_search_classes_placeholder: 'Search classes...',
    sa_nuke_confirm: '⚠️ DELETE ALL USER DATA?\nThis CANNOT be undone!',
    sa_nuke_disabled: 'This feature is disabled for security.',
    sa_add_admin_placeholder: 'Email of new admin',
    sa_add_admin_btn: 'Add Admin',
    sa_revoke_btn: 'Revoke',
    sa_no_admins: 'No superadmins registered yet.',
    sa_max_classes_saved: 'Class limit setting saved (local).',
    sa_max_students_saved: 'Student limit setting saved (local).',
  },
  id: {
    tab_seating: 'Tempat Duduk', tab_picker: 'Acak Nama',
    pov_teacher: 'POV Guru', pov_student: 'POV Siswa',
    pov_teacher_label: 'Tampilan Guru', pov_student_label: 'Tampilan Siswa',
    btn_shuffle: 'Acak', btn_skip_anim: 'Skip', btn_students: 'Siswa', btn_settings: 'Pengaturan',
    btn_apply: 'Terapkan', btn_done: 'Selesai', btn_cancel: 'Batal', btn_save: 'Simpan',
    btn_close: 'Tutup', btn_export: 'Ekspor', btn_import: 'Impor',
    btn_pick: 'Pilih!', btn_clear_history: 'Hapus Riwayat',
    btn_add_student: 'Tambah Siswa', btn_bulk_add: 'Simpan Daftar',
    btn_stats: 'Statistik', btn_undo_pick: 'Undo', btn_sort_alpha: 'A-Z', btn_sort_status: 'Status',
    stat_total: 'Total Siswa', stat_present: 'Hadir', stat_absent: 'Absen',
    stat_seats: 'Bangku Aktif', stat_occupancy: 'Terisi',
    btn_all_present: '✓ Semua Hadir', btn_all_absent: '✗ Semua Absen',
    btn_reset: 'Reset Default', btn_upload_bg: 'Unggah', btn_clear_bg: 'Hapus',
    btn_clear_all: 'Hapus Semua',
    seating_title: 'Denah Tempat Duduk', teacher_desk: '🖥️ Meja Guru',
    label_rows: 'Baris:', label_cols: 'Kolom:', label_name: 'Nama Lengkap',
    label_gender: 'Jenis Kelamin', label_status: 'Kehadiran', label_bulk: 'Nama Siswa',
    opt_male: 'Laki-laki', opt_female: 'Perempuan', opt_present: 'Hadir', opt_absent: 'Absen',
    hint_bulk: 'Edit bebas. Nama baru ditambahkan, nama dihapus akan dihapus, nama lama dipertahankan.',
    modal_students_title: 'Kelola Siswa', modal_edit_title: 'Edit Siswa',
    modal_settings_title: 'Pengaturan',
    stab_list: 'Daftar Siswa', stab_add: 'Tambah Siswa', stab_bulk: 'Tambah Massal',
    picker_title: '🎲 Acak Nama',
    picker_subtitle: 'Memilih siswa secara acak dari yang hadir',
    picker_placeholder: 'Tekan Pilih untuk mulai!',
    allow_repeat: 'Izinkan pengulangan',
    history_title: 'Riwayat Pilihan', history_empty: 'Belum ada pilihan. Mulai pilih!',
    settings_data: 'Manajemen Data', settings_appearance: 'Tampilan', settings_danger: 'Zona Berbahaya',
    settings_export: 'Ekspor Data', settings_export_desc: 'Simpan semua data sebagai file .json',
    settings_import: 'Impor Data', settings_import_desc: 'Muat file .json yang sebelumnya diekspor',
    settings_bg: 'Latar Belakang Kustom', settings_bg_desc: 'Unggah gambar sebagai latar halaman (dikompres otomatis)',
    settings_pov: 'Sudut Pandang', settings_pov_desc: 'Balik orientasi denah tempat duduk',
    settings_clear_all: 'Hapus Semua Data', settings_clear_all_desc: 'Hapus semua data localStorage dan reset ke default',
    ctx_lock: 'Kunci Kursi', ctx_unlock: 'Buka Kunci',
    ctx_disable: 'Nonaktifkan Kursi', ctx_enable: 'Aktifkan Kursi',
    ctx_gender: 'Ganti Jenis Kelamin', ctx_assign: 'Tugaskan Siswa',
    word_students: 'siswa', word_undo: 'Undo',
    btn_attendance: 'Absensi', btn_view_rekap: 'Lihat Rekap',
    btn_rekap_nilai: 'Rekap Nilai', modal_rekap_nilai_title: 'Rekap Nilai',
    lbl_include_zero: 'Ikutkan nilai 0',
    tab_nilai_siswa: 'Per Siswa', tab_nilai_hari: 'Per Hari',
    tab_nilai_minggu: 'Per Minggu', tab_nilai_ringkasan: 'Ringkasan',
    lbl_quiz_weekly: 'Kuis Mingguan', lbl_quiz_daily: 'Kuis Harian',
    lbl_nilai_label: 'Nilai', lbl_avg: 'Rata-rata',
    lbl_weekly_avg: 'Rata Minggu', lbl_class_avg: 'Rata Kelas',
    lbl_no_nilai: 'Belum ada data nilai.',
    toast_nilai_saved: 'Nilai tersimpan!', settings_rekap_desc: 'Lihat & cetak rekap absensi per periode', modal_attendance_title: 'Absensi Harian',
    modal_rekap_title: 'Rekap Absensi', label_att_date: 'Tanggal',
    btn_all_hadir: 'Semua Hadir', btn_all_alpa: 'Semua Alpa',
    btn_save_att: 'Simpan Absensi', btn_filter: 'Filter',
    btn_print: 'Cetak', btn_del_date: 'Hapus Tanggal',
    att_hadir: 'Hadir', att_sakit: 'Sakit', att_izin: 'Izin', att_alpa: 'Alpa',
    btn_edit_formasi: 'Edit Formasi', btn_done_formasi: '✓ Selesai',
    btn_mark_absent_one: 'Tandai Absen', btn_mark_present_one: 'Tandai Hadir',
    toast_att_saved: 'Absensi tersimpan!', toast_att_deleted: 'Tanggal dihapus.',
    toast_att_no_date: 'Pilih tanggal terlebih dahulu.',
    rekap_no_data: 'Belum ada data absensi.',
    col_name: 'Nama', col_total_H: 'Hadir', col_total_S: 'Sakit',
    col_total_I: 'Izin', col_total_A: 'Alpa', col_total: 'Total',
    row_summary: 'Rekapan',
    toast_undo_empty: 'Belum ada pilihan untuk di-undo.',
    toast_sort_alpha: 'Diurutkan A-Z.', toast_sort_status: 'Diurutkan berdasarkan status.',
    toast_reset_confirm: 'Reset ke siswa default?',
    toast_clear_confirm: 'Ini akan menghapus SEMUA data. Lanjutkan?',
    toast_bg_uploading: 'Menyimpan background ke cloud...',
    toast_bg_local: 'Background tersimpan lokal saja.',
    toast_fix_gender: 'gender diperbarui!', toast_fix_gender_ok: 'Semua gender sudah benar.',
    toast_class_delete_confirm: 'Hapus kelas? Data tidak bisa dikembalikan.',
    toast_class_empty_name: 'Isi nama kelas dulu!',
    sync_saving: 'Menyimpan', sync_saved: 'Online', sync_error: 'Gagal sinkron', sync_offline: 'Offline',
    picker_eligible: 'tersedia', picker_picks: 'pilihan',
    toast_shuffled: 'Tempat duduk diacak!', toast_locked_seats: 'kursi terkunci dipertahankan.',
    toast_no_students: 'Tidak ada siswa hadir untuk diacak.',
    toast_student_added: 'Siswa ditambahkan!', toast_student_updated: 'Siswa diperbarui!',
    toast_student_deleted: 'Siswa dihapus.',
    toast_bulk_added: 'siswa ditambahkan!', toast_all_present: 'Semua siswa ditandai hadir.',
    word_added: 'ditambahkan', word_removed: 'dihapus', word_total: 'total',
    toast_all_absent: 'Semua siswa ditandai absen.',
    toast_reset: 'Direset ke siswa default.',
    toast_exported: 'Data berhasil diekspor!', toast_imported: 'Data berhasil diimpor!',
    toast_import_error: 'File tidak valid. Gagal mengimpor.',
    toast_bg_set: 'Gambar latar berhasil diatur!', toast_bg_cleared: 'Latar dihapus.',
    toast_cleared: 'Semua data dihapus. Mulai baru!',
    toast_no_eligible: 'Tidak ada siswa yang bisa dipilih!',
    toast_all_picked: 'Semua siswa sudah dipilih! Hapus riwayat atau aktifkan pengulangan.',
    status_present: 'Hadir', status_absent: 'Absen',
    eligible_label: 'tersedia',
    picks_label: 'pilihan',
    // Superadmin panel strings
    sa_title: 'Panel Superadmin',
    sa_loading: 'Memuat...',
    sa_loading_users: 'Memuat daftar pengguna...',
    sa_loading_classes: 'Memuat semua kelas...',
    sa_loading_class: 'Memuat kelas...',
    sa_loading_class_data: 'Memuat data kelas...',
    sa_no_users: 'Tidak ada pengguna ditemukan.',
    sa_no_classes: 'Belum ada kelas terdaftar.',
    sa_no_classes_match: 'Tidak ada kelas yang cocok.',
    sa_no_user_classes: 'User ini belum punya kelas.',
    sa_no_att_data: 'Belum ada data absensi.',
    sa_no_score_data: 'Belum ada data nilai.',
    sa_no_students: 'Tidak ada siswa.',
    sa_you_label: 'Kamu',
    sa_view_classes_btn: '�� Kelas',
    sa_promote_btn: '⬆ Jadikan Admin',
    sa_demote_btn: '⬇ Jadikan User',
    sa_confirm_revoke_admin: 'Cabut hak superadmin user ini?',
    sa_role_changed: 'Role diubah menjadi "{role}".',
    sa_err_change_role: 'Gagal ubah role: ',
    sa_err_load: 'Gagal memuat: ',
    sa_err_delete_class: 'Gagal hapus: ',
    sa_confirm_delete_class: 'Hapus kelas "{name}" milik {user}?\nData akan hilang permanen.',
    sa_class_deleted: 'Kelas "{name}" dihapus.',
    sa_classes_summary: 'Total',
    sa_classes_summary2: 'pengguna',
    sa_classes_owned_by: 'Kelas milik:',
    sa_back_to_users: '← Kembali ke Pengguna',
    sa_back_to_classes: '← Kembali',
    sa_by: 'oleh',
    sa_update: 'Update:',
    sa_col_students: 'Siswa',
    sa_col_att_days: 'Hari Absensi',
    sa_col_score_days: 'Hari Nilai',
    sa_tab_rekap_att: '📋 Rekap Absensi',
    sa_tab_rekap_nilai: '📊 Rekap Nilai',
    sa_tab_students: '👥 Daftar Siswa',
    sa_create_class_btn: 'Buat Kelas',
    sa_footer: 'Hanya superadmin yang bisa mengakses panel ini.',
    sa_lbl_recent_activity: 'Aktivitas terbaru',
    sa_tab_dashboard: 'Dashboard',
    sa_tab_users: 'Pengguna',
    sa_tab_classes: 'Kelas',
    sa_tab_logs: 'Log',
    sa_tab_settings: 'Pengaturan',
    sa_lbl_total_users: 'Total Pengguna',
    sa_lbl_total_classes: 'Total Kelas',
    sa_lbl_total_students: 'Total Siswa',
    sa_lbl_active_today: 'Aktif Hari Ini',
    sa_lbl_recent_users: 'Pengguna Terbaru',
    sa_search_users_placeholder: 'Cari pengguna...',
    sa_search_classes_placeholder: 'Cari kelas...',
    sa_nuke_confirm: '⚠️ HAPUS SEMUA DATA USER?\nIni TIDAK BISA dibatalkan!',
    sa_nuke_disabled: 'Fitur ini dinonaktifkan demi keamanan.',
    sa_add_admin_placeholder: 'Email admin baru',
    sa_add_admin_btn: 'Tambah Admin',
    sa_revoke_btn: 'Cabut',
    sa_no_admins: 'Belum ada superadmin terdaftar.',
    sa_max_classes_saved: 'Pengaturan batas kelas disimpan (lokal).',
    sa_max_students_saved: 'Pengaturan batas siswa disimpan (lokal).',
  },
  ja: {
    tab_seating: '座席表', tab_picker: '名前くじ',
    pov_teacher: '先生視点', pov_student: '生徒視点',
    pov_teacher_label: '先生', pov_student_label: '生徒',
    btn_shuffle: 'シャッフル', btn_skip_anim: 'スキップ', btn_students: '生徒', btn_settings: '設定',
    btn_apply: '適用', btn_done: '完了', btn_cancel: 'キャンセル', btn_save: '変更を保存',
    btn_close: '閉じる', btn_export: 'エクスポート', btn_import: 'インポート',
    btn_pick: 'くじを引く', btn_clear_history: '履歴を消す',
    btn_add_student: '生徒を追加', btn_bulk_add: 'リストを保存',
    btn_stats: '統計', btn_undo_pick: '元に戻す', btn_sort_alpha: 'A-Z', btn_sort_status: '状態順',
    stat_total: '生徒数合計', stat_present: '出席', stat_absent: '欠席',
    stat_seats: '有効な席', stat_occupancy: '在席率',
    btn_all_present: '✓ 全員出席', btn_all_absent: '✗ 全員欠席',
    btn_reset: '初期設定に戻す', btn_upload_bg: 'アップロード', btn_clear_bg: '消去',
    btn_clear_all: '全て消去',
    seating_title: '座席表', teacher_desk: '🖥️ 先生の机',
    label_rows: '行:', label_cols: '列:',
    label_name: '氏名', label_gender: '性別', label_status: '出席状況',
    label_bulk: '生徒氏名', label_att_date: '日付',
    opt_male: '男子', opt_female: '女子',
    opt_present: '出席', opt_absent: '欠席',
    hint_bulk: '自由に編集。新しい名前は追加、消えた名前は削除されます。',
    modal_students_title: '生徒管理', modal_edit_title: '生徒を編集',
    modal_settings_title: '設定',
    stab_list: '生徒一覧', stab_add: '生徒を追加', stab_bulk: '一括追加',
    picker_title: '🎲 名前くじ',
    picker_subtitle: '出席中の生徒からランダムに選びます',
    picker_placeholder: 'ボタンを押してスタート！',
    allow_repeat: '同じ生徒を繰り返し選ぶ',
    history_title: 'くじ履歴', history_empty: 'まだ選んでいません。',
    settings_data: 'データ管理', settings_appearance: '外観',
    settings_danger: '危険ゾーン',
    settings_export: 'データをエクスポート',
    settings_export_desc: 'データをJSONファイルとして保存',
    settings_import: 'データをインポート',
    settings_import_desc: 'JSONファイルを読み込む',
    settings_bg: 'カスタム背景',
    settings_bg_desc: '背景画像をアップロード（自動圧縮）',
    settings_pov: '視点', settings_pov_desc: '席の向きを反転',
    settings_clear_all: '全データを消去',
    settings_clear_all_desc: 'ローカルデータをリセット',
    settings_rekap_desc: '出席レポートを表示・印刷',
    ctx_lock: '席を固定', ctx_unlock: '固定を解除',
    ctx_disable: '席を無効化', ctx_enable: '席を有効化',
    ctx_gender: '性別を変更', ctx_assign: '生徒を割り当て',
    word_students: '人', word_undo: '元に戻す',
    btn_attendance: '出席', btn_view_rekap: 'レポートを見る',
    btn_rekap_nilai: '成績レポート', modal_rekap_nilai_title: '成績レポート',
    lbl_include_zero: '0点を含める',
    tab_nilai_siswa: '生徒別', tab_nilai_hari: '日別',
    tab_nilai_minggu: '週別', tab_nilai_ringkasan: 'まとめ',
    lbl_quiz_weekly: '週間テスト', lbl_quiz_daily: '日課テスト',
    lbl_nilai_label: '点数', lbl_avg: '平均',
    lbl_weekly_avg: '週平均', lbl_class_avg: 'クラス平均',
    lbl_no_nilai: 'まだ成績データがありません。',
    toast_nilai_saved: '成績を保存しました！',
    modal_attendance_title: '出席入力',
    modal_rekap_title: '出席レポート',
    btn_all_hadir: '✓ 全員出席', btn_all_alpa: '✗ 全員欠席',
    btn_save_att: '出席を保存', btn_filter: '絞り込み',
    btn_print: '印刷', btn_del_date: '日付を削除',
    att_hadir: '出席', att_sakit: '病欠', att_izin: '公欠', att_alpa: '無断欠席',
    btn_edit_formasi: '席を編集', btn_done_formasi: '✓ 完了',
    btn_mark_absent_one: '欠席にする', btn_mark_present_one: '出席にする',
    toast_att_saved: '出席を保存しました！',
    toast_att_deleted: '日付を削除しました。',
    toast_att_no_date: '先に日付を選んでください。',
    rekap_no_data: 'まだ出席データがありません。',
    col_name: '氏名', col_total_H: '出席', col_total_S: '病欠',
    col_total_I: '公欠', col_total_A: '無断', col_total: '合計',
    row_summary: '合計',
    toast_undo_empty: '元に戻す操作がありません。',
    toast_sort_alpha: 'A-Z順に並べました。',
    toast_sort_status: '状態順に並べました。',
    toast_reset_confirm: '初期設定の生徒に戻しますか？',
    toast_clear_confirm: '全てのデータを消去します。よろしいですか？',
    toast_bg_uploading: '背景をクラウドに保存中...',
    toast_bg_local: '背景はローカルのみに保存されました。',
    toast_fix_gender: '人の性別を更新しました！',
    toast_fix_gender_ok: '全ての性別は正しく設定されています。',
    toast_class_delete_confirm: 'クラスを削除しますか？データは復元できません。',
    toast_class_empty_name: 'クラス名を入力してください。',
    sync_saving: '保存中', sync_saved: 'オンライン',
    sync_error: '同期失敗', sync_offline: 'オフライン',
    picker_eligible: '人', picker_picks: '回',
    toast_shuffled: '席をシャッフルしました！',
    toast_locked_seats: '席は固定されています。',
    toast_no_students: 'シャッフルできる出席者がいません。',
    toast_student_added: '生徒を追加しました！',
    toast_student_updated: '生徒情報を更新しました！',
    toast_student_deleted: '生徒を削除しました。',
    toast_bulk_added: '人を追加しました！',
    toast_all_present: '全員を出席にしました。',
    word_added: '追加', word_removed: '削除', word_total: '合計',
    toast_all_absent: '全員を欠席にしました。',
    toast_reset: '初期設定の生徒に戻しました。',
    toast_exported: 'データをエクスポートしました！',
    toast_imported: 'データをインポートしました！',
    toast_import_error: 'ファイルが無効です。インポートできません。',
    toast_bg_set: '背景画像を設定しました！',
    toast_bg_cleared: '背景を削除しました。',
    toast_cleared: '全データを消去しました。',
    toast_no_eligible: '選べる生徒がいません！',
    toast_all_picked: '全員を選びました！履歴を消すか繰り返しを有効にしてください。',
    status_present: '出席', status_absent: '欠席',
    eligible_label: '人', picks_label: '回',
    // Superadmin panel strings
    sa_title: 'スーパー管理パネル',
    sa_loading: '読み込み中...',
    sa_loading_users: 'ユーザーを読み込み中...',
    sa_loading_classes: 'すべてのクラスを読み込み中...',
    sa_loading_class: 'クラスを読み込み中...',
    sa_loading_class_data: 'クラスデータを読み込み中...',
    sa_no_users: 'ユーザーが見つかりません。',
    sa_no_classes: '登録されたクラスはまだありません。',
    sa_no_classes_match: '一致するクラスはありません。',
    sa_no_user_classes: 'このユーザーにはクラスがありません。',
    sa_no_att_data: '出席データはまだありません。',
    sa_no_score_data: '成績データはまだありません。',
    sa_no_students: '生徒がいません。',
    sa_you_label: 'あなた',
    sa_view_classes_btn: '📚 クラス',
    sa_promote_btn: '⬆ 管理者にする',
    sa_demote_btn: '⬇ ユーザーにする',
    sa_confirm_revoke_admin: 'このユーザーのスーパー管理者権限を削除しますか？',
    sa_role_changed: 'ロールが「{role}」に変更されました。',
    sa_err_change_role: 'ロール変更に失敗: ',
    sa_err_load: '読み込みに失敗: ',
    sa_err_delete_class: '削除に失敗: ',
    sa_confirm_delete_class: '{user}のクラス「{name}」を削除しますか？\nデータは完全に失われます。',
    sa_class_deleted: 'クラス「{name}」を削除しました。',
    sa_classes_summary: '合計',
    sa_classes_summary2: 'ユーザー',
    sa_classes_owned_by: 'クラスの所有者:',
    sa_back_to_users: '← ユーザーに戻る',
    sa_back_to_classes: '← 戻る',
    sa_by: '作成者',
    sa_update: '更新:',
    sa_col_students: '生徒',
    sa_col_att_days: '出席日数',
    sa_col_score_days: '成績日数',
    sa_tab_rekap_att: '📋 出席レポート',
    sa_tab_rekap_nilai: '📊 成績レポート',
    sa_tab_students: '👥 生徒一覧',
    sa_create_class_btn: 'クラスを作成',
    sa_footer: 'このパネルはスーパー管理者のみアクセスできます。',
    sa_lbl_recent_activity: '最近のアクティビティ',
    sa_tab_dashboard: 'ダッシュボード',
    sa_tab_users: 'ユーザー',
    sa_tab_classes: 'クラス',
    sa_tab_logs: 'ログ',
    sa_tab_settings: '設定',
    sa_lbl_total_users: '合計ユーザー',
    sa_lbl_total_classes: '合計クラス',
    sa_lbl_total_students: '合計生徒',
    sa_lbl_active_today: '本日のアクティブ',
    sa_lbl_recent_users: '最新ユーザー',
    sa_search_users_placeholder: 'ユーザーを検索...',
    sa_search_classes_placeholder: 'クラスを検索...',
    sa_nuke_confirm: '⚠️ すべてのユーザーデータを削除しますか？\nこの操作は元に戻せません！',
    sa_nuke_disabled: 'セキュリティのためこの機能は無効です。',
    sa_add_admin_placeholder: '新しい管理者のメール',
    sa_add_admin_btn: '管理者を追加',
    sa_revoke_btn: '取り消し',
    sa_no_admins: 'スーパー管理者はまだ登録されていません。',
    sa_max_classes_saved: 'クラス制限設定を保存しました（ローカル）。',
    sa_max_students_saved: '生徒制限設定を保存しました（ローカル）。',
  },
};
